### ISSUE TITLE
Cannot find module 'pixi-scrollbox'

### ISSUE THREAD

**Issue by gsknbabu** [davidfig/pixi-scrollbox#1]
Hi,
I am trying to get the scrollbox using angular4 application. I am getting the error 'Cannot find module pixi-scrollbox'.

I did 'npm install pixi-scrollbox' and using in component as
import * as Scrollbox from 'pixi-scrollbox'
 
Environment:
Pixi: 4.8.1
Pixi-scrollbox: 1.1.0
Angular : 4.2.4
Angular CLI : 1.7.3

Thanks,
Naveen.

**Comment by davidfig** [comment]
pixi-scrollbox currently does not support angular. I don't know much about angular or how to support it, but would be happy to include it if you want to help.
