### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by c-andrews** [davidfig/pixi-scrollbox#10]
Can you able to tell me if `scrollbox` supports TypeScript as i cant find a index.d.ts?

**Comment by davidfig** [comment]
It does not but I would love to add it. I don't have time right now, however.

**Comment by jeanbenitez** [comment]
@davidfig, do you wanna migrate project to typescript or to add type definitions?

**Comment by davidfig** [comment]
Just add type definitions for now. Thanks!

**Comment by c-andrews** [comment]
@jeanbenitez did you manage to add in the Type Definitions? Thanks!

**Comment by jeanbenitez** [comment]
TBH, no, I'm sorry, I haven't had time. Go ahead! I guess you could add a label to mark it as In Progress 😃
