### ISSUE TITLE
Manually set scroll position?

### ISSUE THREAD

**Issue by Losses** [davidfig/pixi-scrollbox#26]
Trying something like:
```
scrollBox.scrollLeft = 0
```
But got:
Uncaught TypeError: Cannot set property scrollLeft of #<Scrollbox> which has only a getter

It's weird...

**Comment by davidfig** [comment]
That's because I didn't have setters for scrollLeft and scrollTop. I added them in v2.2.0. Let me know if you have any problems.

**Comment by Losses** [comment]
it works! thank you!
