### ISSUE TITLE
Infinite scroll when `dragScroll` is disabled

### ISSUE THREAD

**Issue by todoroff** [davidfig/pixi-scrollbox#27]
I'm only using a horizontal scrollbar and I'm getting an infinite scroll when I set `dragScroll` to `false`. In other words I can keep scrolling past the `scrollWidth`. 
I can scroll as much as I want to the left and until the scrollbar disappears to the right (but still well past the required `scrollWidth`).

I wonder if it could be related to the `_bounds` property's values, although those look exactly the same with or without drag enabled?

![image](https://user-images.githubusercontent.com/48935314/100136581-2158e700-2e83-11eb-8164-5549d366796b.png)

**Comment by davidfig** [comment]
Definitely a bug. I wasn't clamping the viewport when `options.dragScroll=false`. I fixed it in v2.2.1.

**Comment by todoroff** [comment]
Neat! Would you mind pushing it to npm as well? Cheers

**Comment by davidfig** [comment]
Weird. I thought I had published it to npm. It's now there as 2.2.1.
