### ISSUE TITLE
Can ScrollView's Scrollbox set as a sprite?

### ISSUE THREAD

**Issue by c8827595** [davidfig/pixi-scrollbox#29]
The ScrollView is great, but i wanna use sprite to set my scrollbar , is this possible?

**Comment by davidfig** [comment]
What do you mean using a sprite to set the scrollbar?

**Comment by c8827595** [comment]
Like a png that can be set as a scrollbar and the bar will scale that sprite if scrolling.
is this possoble?
Sorry about my poor English.

**Comment by davidfig** [comment]
It's possible, but would be difficult to build in to the API. Instead, you should overwrite the `_drawScrollbars()` function in Scrollbox (easiest way is to create your own class: `class MyScrollbox extends Scrollbox`). 

Then overwrite `_drawScrollbars` using my function as the base of your derived function. Replace my `.beginFill` commands with `.beginTextureFill`. It'll take a bit of work to get it right but it should provide the desired functionality.

**Comment by c8827595** [comment]
I'll try your way, thanks.

export class MyScrollbox extends Scrollbox {
  constructor(options?: ScrollBoxOptions) {
    super(options);
  }
}

but when i overwrite the class in typescript. it shows

Uncaught TypeError: Class constructor Scrollbox cannot be invoked without 'new'

Do you have some solution for this problem?
My project's compile target is ES5

**Comment by davidfig** [comment]
Did you try it without overwriting the constructor? You don't need to change it.

**Comment by c8827595** [comment]
hmmm.. Seems like the same error as soon as 

export class MyScrollbox extends Scrollbox {}

**Comment by c8827595** [comment]
I installed from npm, and use typescript.
and i entends the pixi's container is working.
but {Viewport} and {scrollbox} will show Uncaught TypeError: Class constructor Scrollbox cannot be invoked without 'new'

Because those are ES6 classes?

**Comment by davidfig** [comment]
Not sure. You can also try to overwrite the prototype after instantiation: scrollbox._drawScrollbars = () => {}. I try not to use typescript because I run into too many of these problems.
