### ISSUE TITLE
Sprites with negative positions not visible in the viewport

### ISSUE THREAD

**Issue by fix777** [davidfig/pixi-scrollbox#37]
Here is a [CodeSandbox](https://codesandbox.io/s/pixi-scrollbox-negative-positioned-sprites-qnkd2).
I give 2 Sprites in the CodeSandbox:
- Sprite1: [-200, -200]
- Sprite2: [600, 600]
then the Sprite1 is not show up on the scrollbox.
Can you give me some help?

**Comment by davidfig** [comment]
Ah. Scrollbox assumes your top-left corner is 0, 0. The underlying viewport that scrollbox is based on handles negative values fine, it's just the scrollbox calculations for scrollbars and clamping and such that limit the top-left value. It's possible to tweak the code to allow for arbitrary corners, but I currently don't have plans to do so. I'm happy to take a PR if you're interested. 

The easiest way to hack it is to normalize your items. Search through the items and find the smallest x and y. If the smallest value is < 0 then add the negative amount to all items.

A more complicated approach that takes into account rotations and such is to find the bounding box of scrollbox.content (the viewport inside the scrollbox), and then change its position by the negative top-left value in the same way. There'll likely be some tweaking necessary for this to work.

Good luck!

**Comment by fix777** [comment]
Thanks, David, I will give it a try.
Closing for now.
