### ISSUE TITLE
JS downloadables in the latest release are messed up

### ISSUE THREAD

**Issue by boyanl** [davidfig/pixi-scrollbox#6]
Both `scrollbox.js` and `scrollbox.min.js` in the [1.6.0 release](https://github.com/davidfig/pixi-scrollbox/releases/tag/1.6.0) are actually HTML files.
(e.g. first few lines of the minified one are: 
    
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="utf-8">

.. etc)

**Comment by davidfig** [comment]
Yup. Definitely messed up. Working on updating and fixing old dependencies.

**Comment by davidfig** [comment]
I added a 2.0.0 release with (hopefully) working files. Please let me know if you have any further issues.

**Comment by boyanl** [comment]
Yep, all fine now. Thanks!
